version: '3.8'
services:
      app:
        build: .
        # command: ["make", "gunicorn-dev"]
        command: /bin/bash -c "pkill gunicorn || true && poetry run gunicorn -c gunicorn.dev.py && tail -f ./var/log/gunicorn/dev.log"
        env_file:
          - ./.env
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        volumes:
          - ./:/usr/src/app/
        ports:
         - "8000:8000"
        restart: always
        depends_on:
         - db
      db:
        image: postgres:15
        restart: always
        volumes:
         - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ./.env
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: