version: '3.8'
services:
      foundationbackend:
        build: .
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        command: make gunicorn-dev
        volumes:
          - ./:/usr/src/app/
        ports:
         - "8000:8000"
        restart: always
        env_file:
          - ./.env
        depends_on:
         - db
      db:
        image: postgres:15Ss
        restart: always
        volumes:
         - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ./.env
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: