version: '3.8'

services:
  foundationbackend:
    build: ./
    image: foundationbackend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: poetry shell
    command: make gunicorn-dev
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  