name: CICD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker Compose
              run: |
                echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
                echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
                echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
                echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
                docker-compose -f docker-compose-prod.yml build
                docker tag foundation_backend_app:latest ilijapetro/foundation_backend_app:latest
                docker push ilijapetro/foundation_backend_app:latest
    deploy:
        needs: build
        runs-on: aws-ec2-back
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Create .env file
              run: |
                echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
                echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
                echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
                echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
          
            - name: delete Docker image
              run: docker rm -f foundation_backend_app || true
            - name: Pull Docker image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/foundation_backend_app:latest
            - name: Create app-network
              run: docker network create app-network || true
            # - name: Run Docker image
            #   run: sudo docker run -d -p 8000:8000 --name foundation_backend_app ${{ secrets.DOCKER_USERNAME }}/foundation_backend_app:latest
            - name: Run Docker image app
              run: docker run -d -p 8000:8000 --name app --network app-network --env-file ./.env ${{ secrets.DOCKER_USERNAME }}/foundation_backend_app:latest
            - name: Run Docker image dv
              run: docker run -d --name db --network app-network --env-file ./.env ${{ secrets.DOCKER_USERNAME }}/foundation_backend_app:latest
