name: CICD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker Compose
              run: |
                echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
                echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
                echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
                docker-compose -f docker-compose-prod.yml build foundation_backend
                docker tag backend_foundation_backend:latest ilijapetro/backend_foundation_backend:latest
                docker push ilijapetro/backend_foundation_backend:latest
    deploy:
        needs: build
        runs-on: aws-ec2-back
        steps:
            - name: delete Docker image
              run: sudo docker rm -f foundation_backend || true
            - name: Pull Docker image
              run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foundation_backend:latest
            - name: Run Docker image
              run: sudo docker run -d -p 8000:8000 --name foundation_backend ${{ secrets.DOCKER_USERNAME }}/foundation_backend:latest
